ts1/ts1/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/',include('tss1.urls'))
]

ts1/tss1/urls.py
from django.urls import path
from .views import home,doctor

app_name='tss1'
urlpatterns=[
    path('',home,name="home"),
    path('doctor/',doctor,name="doctor")
]

ts1/tss1/models.py
from django.db import models
from django.db import models
from django.db.models.fields import CharField

# Create your models here.
choice=(
    ('D','doctor'),
    ('P','patient')
)
class userdetails(models.Model):
    firstname=models.CharField(max_length=100)
    lastname=models.CharField(max_length=10)
    email=models.EmailField()
    number=models.BigIntegerField()
    type=models.CharField(choices=choice,max_length=10)

    def _str_(self):
        return self.firstname

ts1/tss1/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import userdetails


# Create your views here.

def home(request):
    if request.method=='POST':
        if request.POST['type']=='doctortype':
           return render(request,"tss1/doctor.html")
        elif request.POST['type']=='patienttype':
            return render(request,"tss1/patient.html")   
             
    else:
        return render(request,"tss1/index.html") 

def doctor(request):
    if request.method=='POST':
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        email=request.POST['email']
        number=request.POST['number']
        type=request.POST['type']
        user=userdetails.objects.create(firstname=firstname,lastname=lastname,email=email,number=number,type=type)
        user.save()
        return HttpResponse("Congratulations! User created succesfully")

ts1/tss1/templates/tss1/doctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
   <style>
    form {margin:auto ;
      width:250px;
      text-align: center;

    }
 </style>
</head>

<body>
  <h1 class="text-center m-4">Doctor</h1>
  <form method="POST" action="{% url 'tss1:doctor' %}">
    {%csrf_token%}
    <div class="form-row">
        <div class="col">
            <input type="text" class="form-control" placeholder="First name" value='doctor' name="type" hidden>
          </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="First name" name="firstname">
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="Last name" name="lastname">
      </div>
      <div class="col">
        <input type="email" class="form-control" placeholder="email" name="email">
      </div>
      <div class="col">
        <input type="number" class="form-control" placeholder="number" name="number" max="9999999999">
      </div>
      <button class="btn btn-success" style='background-color:cyan'>Submit</button>
    </div>
  </form>    
</body>
</html>

ts1/tss1/templates/tss1/index.html
<html>
    <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
   <style>
    form {margin:auto ;
      width:250px;
      text-align: center;

    }
  </style>
  </head>
    <body>
     
  <div>
  <form action="" method="post">
      {%csrf_token%}
    <div class="form-check">
        <input class="form-check-input" type="radio" name="type" id="exampleRadios1" value="doctortype"  >
        <label class="form-check-label" for="exampleRadios1">
        Doctor
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="type" id="exampleRadios2" value="patienttype">
        <label class="form-check-label" for="exampleRadios2">
         Patient  </label>
      </div>
      <div>
        <button class="btn btn-warning" style='background-color:cyan'>Submit</button>
      </div>
  </form>

  </div>
  
   
    </body>
  </html>

ts1/tss1/templates/tss1/patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  <style>
    form {margin:auto ;
      width:250px;
      text-align: center;

    }
  </style>
</head>

<body>
  <h1 class="text-center m-4">Patient</h1>
  <form method="POST" action="{% url 'tss1:doctor' %}">
    {%csrf_token%}
    <div class="form-row">
        <div class="col">
            <input type="text" class="form-control" placeholder="First name" value='patient' name="type" hidden>
          </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="First name" name="firstname">
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="Last name" name="lastname">
      </div>
      <div class="col">
        <input type="email" class="form-control" placeholder="email" name="email">
      </div>
      <div class="col">
        <input type="number" class="form-control" placeholder="number" name="number" max="9999999999">
      </div>
      <button  class="btn btn-warning" style='background-color:cyan' color='black' >Submit</button>
    </div>
  </form>    
</body>
</html>